- name: Configure Ubuntu dual HDMI setup
  block:
    - name: Add user to video group for framebuffer access
      user:
        name: "{{ service_user }}"
        groups: video
        append: yes
    
    - name: Create framebuffer devices if they don't exist
      shell: |
        if [ ! -e /dev/fb0 ]; then
          mknod /dev/fb0 c 29 0
          chgrp video /dev/fb0
          chmod 664 /dev/fb0
        fi
        if [ ! -e /dev/fb1 ]; then
          mknod /dev/fb1 c 29 32
          chgrp video /dev/fb1
          chmod 664 /dev/fb1
        fi
      become: yes
    
  when: target_os == "ubuntu"

- name: Configure dual HDMI setup
  lineinfile:
    path: "/boot/firmware/config.txt"
    line: '{{ item }}'
    create: yes
  loop:
    - '# Dual HDMI Configuration'
    - '# HDMI0 (primary) - Console/SSH access'
    - 'hdmi_group:0=1'
    - 'hdmi_mode:0=16'
    - '# HDMI1 (secondary) - Slideshow display' 
    - 'hdmi_group:1=1'
    - 'hdmi_mode:1=16'
    - '# Enable both HDMI outputs'
    - 'hdmi_force_hotplug:0=1'
    - 'hdmi_force_hotplug:1=1'
    - '# Use legacy graphics for separate framebuffers'
    - 'dtoverlay=vc4-fkms-v3d'
    - '# Disable KMS overlays to get separate framebuffers'
    - '#dtoverlay=vc4-kms-v3d'
  notify: reboot
  when: target_os == "raspios"

- name: Ensure cmdline.txt exists for raspios
  ansible.builtin.file:
    path: /boot/firmware/cmdline.txt
    state: touch
    mode: '0644'
  when: target_os == "raspios"

- name: Add consoleblank=0 to cmdline.txt
  shell: |
    if ! grep -q "consoleblank=0" /boot/firmware/cmdline.txt; then
      sed -i 's/$/ consoleblank=0/' /boot/firmware/cmdline.txt
    fi
  notify: reboot
  when: target_os == "raspios"