- name: Configure dual HDMI setup
  lineinfile:
    path: "/boot/firmware/config.txt"
    line: '{{ item }}'
    create: yes
  loop:
    - '# Dual HDMI Configuration'
    - 'hdmi_group=2'
    - 'hdmi_mode=16'
    - 'hdmi_force_hotplug=1'
    - '# Use legacy graphics for separate framebuffers'
    - 'dtoverlay=vc4-fkms-v3d'
    - '# Disable KMS overlays to get separate framebuffers'
    - '#dtoverlay=vc4-kms-v3d'
  notify: reboot

- name: Ensure cmdline.txt exists for raspios
  ansible.builtin.file:
    path: /boot/firmware/cmdline.txt
    state: touch
    mode: '0644'

- name: Add consoleblank=0 to cmdline.txt
  shell: |
    if ! grep -q "consoleblank=0" /boot/firmware/cmdline.txt; then
      sed -i 's/$/ consoleblank=0/' /boot/firmware/cmdline.txt
    fi
  notify: reboot
