- name: Check for config.txt location
  stat:
    path: "{{ item }}"
  register: config_locations
  loop:
    - /boot/firmware/config.txt
    - /boot/config.txt

- name: Set boot config path
  set_fact:
    boot_config_path: "{{ item.item }}"
  loop: "{{ config_locations.results }}"
  when: 
    - item.stat.exists

- name: Configure config.txt
  lineinfile:
    path: "{{ boot_config_path }}"
    line: '{{ item }}'
  loop:
    - '# Force both HDMI ports to be active'
    - 'hdmi_force_hotplug=1'
    - 'hdmi_group=2'
    - 'hdmi_mode=16'
    - 'max_framebuffers=2'
    - 'framebuffer_width=1920'
    - 'framebuffer_height=1080'
    - '# Disable KMS overlays to get separate framebuffers'
    - '#dtoverlay=vc4-kms-v3d'
    - '# GPU memory for graphics'
    - 'gpu_mem=128'
    - '# Disable WiFi'
    - 'dtoverlay=disable-wifi'
  notify: reboot
  when: 
    - boot_config_path is defined

- name: Check for cmdline.txt location
  stat:
    path: "{{ item }}"
  register: cmdline_locations
  loop:
    - /boot/firmware/cmdline.txt
    - /boot/cmdline.txt

- name: Set boot cmdline path
  set_fact:
    boot_cmdline_path: "{{ item.item }}"
  loop: "{{ cmdline_locations.results }}"
  when: 
    - item.stat.exists

- name: Add consoleblank=0 to cmdline.txt
  shell: |
    if ! grep -q "consoleblank=0" {{ boot_cmdline_path }}; then
      sed -i 's/$/ consoleblank=0/' {{ boot_cmdline_path }}
    fi
  notify: reboot
  when: 
    - boot_cmdline_path is defined