- name: Deploy configuration file
  template:
    src: slideshow.conf.j2
    dest: /etc/slideshow.conf
    mode: 0644

- name: Deploy slideshow script
  copy:
    src: pillow_slideshow.py
    dest: /usr/local/bin/pillow_slideshow.py
    mode: 0755
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: Deploy HDMI sleep script
  copy:
    src: hdmi_sleep.py
    dest: /usr/local/bin/hdmi_sleep.py
    mode: 0755
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: Create slideshow log file with proper permissions
  file:
    path: /var/log/slideshow.log
    state: touch
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: 0644

- name: Deploy slideshow service
  template:
    src: slideshow.service.j2
    dest: /etc/systemd/system/slideshow.service
    mode: 0644

- name: Deploy HDMI sleep service
  template:
    src: hdmi_sleep.service.j2
    dest: /etc/systemd/system/hdmi_sleep.service
    mode: 0644

- name: Enable and start services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - slideshow
    - hdmi_sleep

- name: Create slideshow manager web directory
  file:
    path: /var/www/html/slideshow_manager
    state: directory
    mode: 0755

- name: Deploy dashboard.html
  copy:
    src: dashboard.html  # Assumes dashboard.html is in the root of the repo, relative to the playbook file
    dest: /var/www/html/slideshow_manager/dashboard.html
    mode: 0644