- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: safe

- name: Install pip and venv
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present

- name: Install Chromium browser
  apt:
    name: chromium-browser
    state: present

- name: Install ChromeDriver
  apt:
    name: chromium-chromedriver
    state: present

- name: Create virtual environment directory
  file:
    path: /opt/slideshow
    state: directory
    mode: 0755

- name: Create Python virtual environment
  command: python3 -m venv {{ venv_path }}
  args:
    creates: "{{ venv_path }}/bin/python"

- name: Install Python libraries in virtual environment
  pip:
    name:
      - pygame
      - requests
      - opencv-python
      - numpy
      - selenium
      - Pillow
      - urllib3
    virtualenv: "{{ venv_path }}"