- name: Detect operating system
  shell: |
    if [ -f /etc/rpi-issue ]; then
      echo "raspios"
    elif grep -q "Ubuntu" /etc/os-release; then
      echo "ubuntu"
    else
      echo "unknown"
    fi
  register: detected_os
  changed_when: false

- name: Set OS fact
  set_fact:
    target_os: "{{ detected_os.stdout }}"

- name: Warn about Ubuntu compatibility
  debug:
    msg: |
      WARNING: Ubuntu detected on Raspberry Pi.
      This system is designed for Raspberry Pi OS. Some features may not work:
      - HDMI power management (vcgencmd)
      - Boot configuration (/boot/config.txt)
      Consider switching to Raspberry Pi OS for full functionality.
  when: target_os == "ubuntu"

- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: safe

- name: Install pip and venv
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present

- name: Install Chromium browser
  apt:
    name: chromium-browser
    state: present

- name: Install ChromeDriver
  apt:
    name: chromium-chromedriver
    state: present

- name: Install OpenGL libraries for OpenCV (Ubuntu)
  apt:
    name:
      - libgl1
      - libglx-mesa0
      - libglib2.0-0
    state: present
  when: target_os == "ubuntu"

- name: Create virtual environment directory
  file:
    path: /opt/slideshow
    state: directory
    mode: 0755

- name: Create Python virtual environment
  command: python3 -m venv {{ venv_path }}
  args:
    creates: "{{ venv_path }}/bin/python"

- name: Install Python libraries in virtual environment
  pip:
    name:
      - pygame
      - requests
      - opencv-python
      - numpy
      - selenium
      - Pillow
      - urllib3
    virtualenv: "{{ venv_path }}"